<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.angelos</groupId>
    <artifactId>koinoxrhsta</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <groupId>com.angelos</groupId>
  <artifactId>CoreKoinoxrhsta</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <name>CoreKoinoxrhsta</name>
  <packaging>jar</packaging>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>com.angelos</groupId>
      <artifactId>InfrastructureKoinoxrhsta</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
</project>
