spring.datasource.url=jdbc:postgresql://localhost:5432/koinoxrhsta
spring.datasource.username=tuser
spring.datasource.password=180295

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-response=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

vaadin.exclude-urls=/api/**