ALTER TABLE koinoxrhsta.tbbill ADD CONSTRAINT FK_TBBILLBUILDINGID FOREIGN KEY (BUILDING_ID) REFERENCES tbbuilding(BUILDING_ID);
ALTER TABLE koinoxrhsta.tbbill ADD CONSTRAINT FK_TBBILLFLATID FOREIGN KEY (FLAT_ID) REFERENCES tbflat(FLAT_ID);
ALTER TABLE koinoxrhsta.tbbill ADD CONSTRAINT FK_TBBILLISSUER FOREIGN KEY (ISSUER_ID) REFERENCES tbissuer(ISSUER_ID);