create table koinoxrhsta.TBBILL (
	RECEIPT_ID INTEGER NOT NULL,
	BUILDING_ID INTEGER,
	FLAT_ID INTEGER,
	ISSUER_ID INTEGER,
	START_DT DATE,
	END_DT DATE,
	DUE_DT DATE,
	REF_RECEIPT_ID INTEGER,
	AMOUNT_CHARGED DECIMAL(10,2),
	AMOUNT_PAID DECIMAL(10,2),
	IS_PAID SMALLINT,
	BUILT_DT DATE
);