create table koinoxrhsta.TBBUILDING (
	BUILDING_ID INTEGER NOT NULL,
	OWNERSHIP_MILLIS INTEGER,
	FLATS SMALLINT,
	FLOORS SMALLINT,
	POSTAL_CODE SMALLINT,
	ADDRESS_NAME VARCHAR(25),
	ADDRESS_NO SMALLINT,
	BUILT_DT DATE
);
