create table koinoxrhsta.TBFLATSPEC (
	BUILDING_ID INTEGER NOT NULL,
	FLAT_ID INTEGER NOT NULL,
	TOTAL_AREA INTEGER,
	BALCONIES_AREA INTEGER,
	BEDROOMS_NO SMALLINT,
	BATHROOMS_NO SMALLINT,
	LIVINGROOMS_NO SMALLINT,
	KITCHENS_NO SMALLINT,
	BALCONIES_NO SMALLINT,
	LAST_VERSION INTEGER
);