create table koinoxrhsta.TBFLAT (
	FLAT_ID INTEGER NOT NULL,
	BUILDING_ID INTEGER NOT NULL,
	OWNER_ID INTEGER,
	OWNERSHIP_MILLIS INTEGER,
	FLOOR SMALLINT,
	FLAT_NAME VARCHAR(2),
	LAST_VERSION INTEGER
);